/**
 * OpCo–partner lane matrix from the OpCo-wise Partner-wise Service listing.
 * Raw pairs are deduped before export as `OPCO_PARTNER_LINK_SEEDS`.
 */

import { dedupeLinks, type SeedLink } from "./helpers";

const RAW_LINKS: SeedLink[] = [
  // zain-kuwait
  ...[
    "actel",
    "arpuplus",
    "bango",
    "blackbox",
    "boku",
    "centili",
    "constantconcept",
    "crowdmedia",
    "dharam",
    "digitalvirgo",
    "dotconvertecs",
    "eklectic",
    "futuratechnologies",
    "google",
    "infomedia",
    "ipification",
    "kgroup",
    "marvel-media",
    "mdg",
    "media-ranch",
    "mediaworld",
    "mobibase",
    "mobilearts",
    "mobimind",
    "nazara",
    "newry",
    "nextboom",
    "numbase",
    "nxtvas",
    "onmobile",
    "qadisha-group",
    "qualtrics",
    "renxo",
    "sammedia",
    "sigma",
    "tangerine",
    "zaingroup",
    "zoodmall",
  ].map((partnerSlug) => ({ opcoSlug: "zain-kuwait", partnerSlug })),

  // zain-ksa
  ...[
    "anghami",
    "arpuplus",
    "bango",
    "centili",
    "ddp",
    "deezer",
    "dharam",
    "digitalvirgo",
    "ebtikar",
    "eklectic",
    "futuratechnologies",
    "gamemine",
    "google",
    "gtaf",
    "infomedia",
    "kgroup",
    "klikomics",
    "marvel-media",
    "media-ranch",
    "mediaworld",
    "mobilearts",
    "newry",
    "novustech",
    "osn",
    "playhera",
    "qualtrics",
    "shahid",
    "starzplay",
    "yandex",
    "zainsd-cp",
    "zoodmall",
  ].map((partnerSlug) => ({ opcoSlug: "zain-ksa", partnerSlug })),

  // zain-jordan
  ...[
    "arpuplus",
    "bango",
    "centili",
    "digitalvirgo",
    "dotconvertecs",
    "gamebar",
    "gamemine",
    "marvel-media",
    "mcp",
    "mediaworld",
    "mobibase",
    "mobilearts",
    "mobimind",
    "novustech",
    "nxtvas",
    "osn",
    "qadisha-group",
    "zaingroup",
    "zainkw",
    "zoodmall",
  ].map((partnerSlug) => ({ opcoSlug: "zain-jordan", partnerSlug })),

  // zain-iraq
  ...[
    "albawaba",
    "alhorizon",
    "bango",
    "blackbox",
    "centili",
    "constantconcept",
    "crosure",
    "crowdmedia",
    "ddp",
    "digitalizehub",
    "digitalvirgo",
    "docomo-digital",
    "dotconvertecs",
    "gamemine",
    "infomedia",
    "ipification",
    "jivamob",
    "klikomics",
    "marvel-media",
    "mcp",
    "mdg",
    "media-ranch",
    "mobibase",
    "mobilearts",
    "mobimind",
    "newry",
    "numbase",
    "parajoy",
    "qadisha-group",
    "qualtrics",
    "sammedia",
    "tangerine",
    "zaingroup",
    "zoodmall",
  ].map((partnerSlug) => ({ opcoSlug: "zain-iraq", partnerSlug })),

  // zain-bahrain
  ...[
    "arpuplus",
    "boku",
    "centili",
    "crowdmedia",
    "digitalvirgo",
    "dotconvertecs",
    "eklectic",
    "eros",
    "futuratechnologies",
    "gamemine",
    "infomedia",
    "jivamob",
    "kgroup",
    "marvel-media",
    "mcp",
    "mediaworld",
    "mobibase",
    "newry",
    "numbase",
    "nxtvas",
    "osn",
    "qadisha-group",
    "qualtrics",
    "sammedia",
    "sigma",
    "tangerine",
    "timwetech",
    "zainbh-otts",
    "zaingroup",
    "zainkw",
  ].map((partnerSlug) => ({ opcoSlug: "zain-bahrain", partnerSlug })),

  // zain-sudan
  ...[
    "arpuplus",
    "bango",
    "digitalvirgo",
    "gamemine",
    "mobilearts",
    "qualtrics",
    "sla-digital",
    "zaingroup",
    "zainkw",
  ].map((partnerSlug) => ({ opcoSlug: "zain-sudan", partnerSlug })),

  // zain-south-sudan (0)
  // no partners in the listing
];

export const OPCO_PARTNER_LINK_SEEDS = dedupeLinks(RAW_LINKS);
