/**
 * Real OpCo-linked partners from the Zain OpCo/Partner roster (variants merged).
 * Extra names appended from the OpCo-wise Partner-wise Service listing.
 */

import type { SeedEntity } from "./helpers";

export const PARTNER_SEEDS: (SeedEntity & { id: number })[] = [
  { id: 1, slug: "albawaba", name: "AlBawaba" },
  { id: 2, slug: "alhorizon", name: "AlHorizon" },
  { id: 3, slug: "anghami", name: "Anghami" },
  { id: 4, slug: "arpuplus", name: "ArpuPlus" },
  { id: 5, slug: "blackbox", name: "Blackbox" },
  { id: 6, slug: "boku", name: "Boku" },
  { id: 7, slug: "centili", name: "Centili" },
  { id: 8, slug: "constantconcept", name: "ConstantConcept" },
  { id: 9, slug: "crosure", name: "Crosure" },
  { id: 10, slug: "crowdmedia", name: "CrowdMedia" },
  { id: 11, slug: "ddp", name: "DDP" },
  { id: 12, slug: "dharam", name: "Dharam" },
  { id: 13, slug: "digitalizehub", name: "DigitalizeHub" },
  { id: 14, slug: "digitalvirgo", name: "DigitalVirgo" },
  { id: 15, slug: "docomo-digital", name: "Docomo Digital" },
  { id: 16, slug: "dotconvertecs", name: "DotConvertecs" },
  { id: 17, slug: "dv-amea", name: "DV-AMEA" },
  { id: 18, slug: "ebtikar", name: "Ebtikar" },
  { id: 19, slug: "eklectic", name: "Eklectic" },
  { id: 20, slug: "futuratechnologies", name: "FuturaTechnologies" },
  { id: 21, slug: "gamemine", name: "Gamemine" },
  { id: 22, slug: "google", name: "Google" },
  { id: 23, slug: "infomedia", name: "Infomedia" },
  { id: 24, slug: "intech", name: "Intech" },
  { id: 25, slug: "jivamob", name: "Jivamob" },
  { id: 26, slug: "kgroup", name: "KGroup" },
  { id: 27, slug: "marvel-media", name: "Marvel Media" },
  { id: 28, slug: "mdg", name: "MDG" },
  { id: 29, slug: "media-ranch", name: "Media Ranch" },
  { id: 30, slug: "mediaworld", name: "MediaWorld" },
  { id: 31, slug: "mobibase", name: "Mobibase" },
  { id: 32, slug: "mobibox", name: "Mobibox" },
  { id: 33, slug: "mobilearts", name: "MobileArts" },
  { id: 34, slug: "mobimind", name: "MobiMind" },
  { id: 35, slug: "newry", name: "Newry" },
  { id: 36, slug: "nextboom", name: "NextBoom" },
  { id: 37, slug: "novustech", name: "Novustech" },
  { id: 38, slug: "numbase", name: "Numbase" },
  { id: 39, slug: "nxtvas", name: "NXTVAS" },
  { id: 40, slug: "onmobile", name: "Onmobile" },
  { id: 41, slug: "osn", name: "OSN" },
  { id: 42, slug: "parajoy", name: "Parajoy" },
  { id: 43, slug: "playhera", name: "PlayHera" },
  { id: 44, slug: "qadisha-group", name: "Qadisha Group" },
  { id: 45, slug: "renxo", name: "Renxo" },
  { id: 46, slug: "sammedia", name: "samMedia" },
  { id: 47, slug: "sigma", name: "sigma" },
  { id: 48, slug: "starzplay", name: "StarzPlay" },
  { id: 49, slug: "tangerine", name: "Tangerine" },
  { id: 50, slug: "teliacom", name: "Teliacom" },
  { id: 51, slug: "track-mobile", name: "Track Mobile" },
  { id: 52, slug: "actel", name: "Actel" },
  { id: 53, slug: "bango", name: "Bango" },
  { id: 54, slug: "deezer", name: "Deezer" },
  { id: 55, slug: "eros", name: "EROS" },
  { id: 56, slug: "gtaf", name: "GTAF" },
  { id: 57, slug: "ipification", name: "Ipification" },
  { id: 58, slug: "klikomics", name: "Klikomics" },
  { id: 59, slug: "mcp", name: "MCP" },
  { id: 60, slug: "nazara", name: "Nazara" },
  { id: 61, slug: "qualtrics", name: "Qualtrics" },
  { id: 62, slug: "shahid", name: "Shahid" },
  { id: 63, slug: "sla-digital", name: "SLA Digital" },
  { id: 64, slug: "timwetech", name: "TimweTech" },
  { id: 65, slug: "yandex", name: "Yandex" },
  { id: 66, slug: "zainbh-otts", name: "ZainBH OTTs" },
  { id: 67, slug: "zaingroup", name: "ZainGroup" },
  { id: 68, slug: "zainkw", name: "ZainKW" },
  { id: 69, slug: "zainsd-cp", name: "ZainSD_CP" },
  { id: 70, slug: "zoodmall", name: "ZoodMall" },
  { id: 71, slug: "karti", name: "Karti" },
  { id: 72, slug: "shofha", name: "Shofha" },
  { id: 73, slug: "gamebar", name: "GameBar" },
];
