import type { SeedEntity } from "./helpers";

export const PARTNER_SEEDS: (SeedEntity & { id: number })[] = [
  { id: 1, slug: "apple", name: "Apple" },
  { id: 2, slug: "google", name: "Google" },
  { id: 3, slug: "digital-virgo", name: "Digital Virgo" },
  { id: 4, slug: "docomo-digital", name: "DOCOMO Digital" },
  { id: 5, slug: "garena", name: "Garena" },
  { id: 6, slug: "lg-uplus", name: "LG U+" },
  { id: 7, slug: "sesame-workshop", name: "Sesame Workshop" },
  { id: 8, slug: "omantel", name: "Omantel" },
  { id: 9, slug: "aduna", name: "Aduna" },
  { id: 10, slug: "apigee", name: "Apigee" },
  { id: 11, slug: "spotify", name: "Spotify" },
  { id: 12, slug: "netflix", name: "Netflix" },
  { id: 13, slug: "deezer", name: "Deezer" },
  { id: 14, slug: "anghami", name: "Anghami" },
  { id: 15, slug: "tencent-cloud", name: "Tencent Cloud" },
  { id: 16, slug: "tencent-games", name: "Tencent Games" },
  { id: 17, slug: "bytedance", name: "ByteDance" },
  { id: 18, slug: "ubisoft", name: "Ubisoft" },
  { id: 19, slug: "electronic-arts", name: "Electronic Arts (EA)" },
  { id: 20, slug: "supercell", name: "Supercell" },
  { id: 21, slug: "riot-games", name: "Riot Games" },
  { id: 22, slug: "epic-games", name: "Epic Games" },
  { id: 23, slug: "unity", name: "Unity" },
  { id: 24, slug: "adjust", name: "Adjust" },
  { id: 25, slug: "appsflyer", name: "AppsFlyer" },
  { id: 26, slug: "braze", name: "Braze" },
  { id: 27, slug: "onesignal", name: "OneSignal" },
  { id: 28, slug: "clevertap", name: "CleverTap" },
  { id: 29, slug: "infobip", name: "Infobip" },
  { id: 30, slug: "sinch", name: "Sinch" },
  { id: 31, slug: "bango", name: "Bango" },
  { id: 32, slug: "fortumo", name: "Fortumo" },
  { id: 33, slug: "meta", name: "Meta" },
  { id: 34, slug: "stripe", name: "Stripe" },
  { id: 35, slug: "paypal", name: "PayPal" },
];
